package be.solidsyntax.xpathperformance;

public enum XPathExpressions {
    ALL_AUTHOR_ELEMENTS_WITHIN_THE_CURRENT_CONTEXT_NOTE_THAT_THIS_IS_EQUIVALENT_TO_THE_EXPRESSION_IN_THE_NEXT_ROW("./author"),
    ALL_AUTHOR_ELEMENTS_WITHIN_THE_CURRENT_CONTEXT("author"),
    ALL_FIRSTNAME_ELEMENTS_WITHIN_THE_CURRENT_CONTEXT("first.name"),
    THE_DOCUMENT_ELEMENT_BOOKSTORE_OF_THIS_DOCUMENT("/bookstore"),
    ALL_AUTHOR_ELEMENTS_IN_THE_DOCUMENT("//author"),
    ALL_BOOK_ELEMENTS_WHOSE_STYLE_ATTRIBUTE_VALUE_IS_EQUAL_TO_THE_SPECIALTY_ATTRIBUTE_VALUE_OF_THE_BOOKSTOREELEMENT_AT_THE_ROOT_OF_THE_DOCUMENT("book[/bookstore/@specialty=@style]"),
    ALL_FIRSTNAME_ELEMENTS_THAT_ARE_CHILDREN_OF_AN_AUTHOR_ELEMENT("author/first-name"),
    ALL_TITLE_ELEMENTS_ONE_OR_MORE_LEVELS_DEEP_IN_THE_BOOKSTORE_ELEMENT_ARBITRARY_DESCENDANTS_NOTE_THAT_THIS_IS_DIFFERENT_FROM_THE_EXPRESSION_IN_THE_NEXT_ROW("bookstore//title"),
    ALL_TITLE_ELEMENTS_THAT_ARE_GRANDCHILDREN_OF_BOOKSTORE_ELEMENTS("bookstore/*/title"),
    ALL_EMPH_ELEMENTS_ANYWHERE_INSIDE_EXCERPT_CHILDREN_OF_BOOK_ELEMENTS_ANYWHERE_INSIDE_THE_BOOKSTOREELEMENT("bookstore//book/excerpt//emph"),
    ALL_TITLE_ELEMENTS_ONE_OR_MORE_LEVELS_DEEP_IN_THE_CURRENT_CONTEXT_NOTE_THAT_THIS_SITUATION_IS_ESSENTIALLY_THE_ONLY_ONE_IN_WHICH_THE_PERIOD_NOTATION_IS_REQUIRED(".//title"),
    ALL_ELEMENTS_THAT_ARE_THE_CHILDREN_OF_AUTHOR_ELEMENTS("author/*"),
    ALL_LASTNAME_ELEMENTS_THAT_ARE_GRANDCHILDREN_OF_BOOK_ELEMENTS("book/*/last-name"),
    ALL_GRANDCHILDREN_ELEMENTS_OF_THE_CURRENT_CONTEXT("*/*"),
    ALL_ELEMENTS_WITH_THE_SPECIALTY_ATTRIBUTE("*[@specialty]"),
    THE_STYLE_ATTRIBUTE_OF_THE_CURRENT_CONTEXT("@style"),
    THE_EXCHANGE_ATTRIBUTE_ON_PRICE_ELEMENTS_WITHIN_THE_CURRENT_CONTEXT("price/@exchange"),
    RETURNS_AN_EMPTY_NODE_SET_BECAUSE_ATTRIBUTES_DO_NOT_CONTAIN_ELEMENT_CHILDREN_THIS_EXPRESSION_IS_ALLOWED_BY_THE_XML_PATH_LANGUAGE_XPATH_GRAMMAR_BUT_IS_NOT_STRICTLY_VALID("price/@exchange/total"),
    ALL_BOOK_ELEMENTS_WITH_STYLE_ATTRIBUTES_OF_THE_CURRENT_CONTEXT("book[@style]"),
    THE_STYLE_ATTRIBUTE_FOR_ALL_BOOK_ELEMENTS_OF_THE_CURRENT_CONTEXT("book/@style"),
    ALL_ATTRIBUTES_OF_THE_CURRENT_ELEMENT_CONTEXT("@*"),
    ALL_FIRST_NAME_ELEMENTS_IN_THE_CURRENT_CONTEXT_NODE_NOTE_THAT_THIS_IS_EQUIVALENT_TO_THE_EXPRESSION_IN_THE_NEXT_ROW("./first-name"),
    ALL_FIRST_NAME_ELEMENTS_IN_THE_CURRENT_CONTEXT_NODE("first-name"),
    THE_FIRST_AUTHOR_ELEMENT_IN_THE_CURRENT_CONTEXT_NODE("author[1]"),
    THE_THIRD_AUTHOR_ELEMENT_THAT_HAS_A_FIRSTNAME_CHILD("author[first-name][3]");

    private String expression;

    XPathExpressions(String expression) {
        this.expression = expression;
    }

    public String expression() {
        return expression;
    }
}
